### ISSUE TITLE
Missing Tools

### ISSUE THREAD

**Issue by evild3ad** [jankais3r/Forensic-Version-Checker#1]
**Mount Image Pro by GetData**
http://www.mountimage.com/
http://www.forensicexplorer.com/download.php --> Other download links

**Autopsy**
https://www.sleuthkit.org/autopsy/download.php
https://github.com/sleuthkit/autopsy/releases/download/autopsy-4.13.0/autopsy-4.13.0-64bit.msi

**The Sleuth Kit**
https://www.sleuthkit.org/sleuthkit/download.php --> Windows Binaries
https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.7.0/sleuthkit-4.7.0-win32.zip

**HstEx by Digital Detective**
https://www.digital-detective.net/digital-forensic-software/hstex/
https://www.digital-detective.net/start/hstex-quick-start/
https://www.digital-detective.net/download/download.php?downcode=v0hm06ql6w57as2r2a3u

**NetAnalysis by Digital Detective**
https://kb.digital-detective.net/display/NetAnalysisV2
https://www.digital-detective.net/start/netanalysis-quick-start/
https://www.digital-detective.net/download/download.php?downcode=jqd2yeglls35jsc0xrpk

Please add an additional checkbox to the GUI (next to "GUI?") to hide/unhide non-existing tools from the list. Would make sense because the list is growing. ;-)

Thank you!

**Comment by jankais3r** [comment]
Thank you for the suggestions.

All implemented in https://github.com/jankais3r/Forensic-Version-Checker/commit/e25d4aeae7ea96db16b071993aa87f830c9644f5.
