### ISSUE TITLE
Adding more tools

### ISSUE THREAD

**Issue by evild3ad** [jankais3r/Forensic-Version-Checker#5]
TZWorks --> Package Builds
https://tzworks.net/prototype_page.php?proto_id=32

AVML
https://github.com/microsoft/avml

LiME
https://github.com/504ensicsLabs/LiME

X-Ways Forensics --> Service Releases (e.g. 19.9 SR-3)
https://www.x-ways.net/winhex/forum/messages/1/5158.html?1579987154

Paraben 3
https://paraben.com/paraben-downloads/
Note: Paraben updated the downloads page. Comes with OneDrive and Google Drive links now.

Thank you!

**Comment by jankais3r** [comment]
AVML, LiME, and TZWorks added in [v1.13](https://github.com/jankais3r/Forensic-Version-Checker/releases/tag/v1.13).

As for X-Ways, I am inclined to not add beta versions of tools for now, as that could double the amount of tools and it is generally not recommended to run beta versions in production environments. Also parsing the forum posts would not be very reliable method, as they do not have a normalized format.

As for Paraben, it was fixed yesterday in a silent `parsers.ini` update. As usual, thank you for suggesting new tools.
